dist: xenial

language: python
python:
  - "3.8.3"

notifications:
  email:
    - powen@renci.org
    - bizon@renci.org
    - kebedey@renci.org
    - patrick@covar.com

# command to install dependencies
install:
  - pip install -r requirements.txt

env:
  global:
    - PYTHONPATH=$PWD

# command to run tests
script:
  - pytest -p no:warnings tests

after_success:
  - coveralls