openapi: 3.0.2
info:
  title: Biolink Model Lookup
  description: 'Utilities for querying the Biolink Model'
  version: '1.0.0'
  contact:
    email: patrick@covar.com
  termsOfService: http://robokop.renci.org:7055/tos?service_long=Biolink+Model+Lookup&provider_long=the+Translator+Consortium
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: lookup
  - name: meta
{% if path is defined -%}
servers:
  - url: "/{{ path }}"
{% endif -%}
paths:
  /bl/{concept}/ancestors:
    get:
      tags:
        - lookup
      summary: 'Return all ancestors (superclasses or superproperties) of concept, based on the BioLink Model YAML.'
      description: ''
      parameters:
        - in: path
          required: true
          name: concept
          default: chemical_substance
        - in: query
          name: version
          default: latest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /bl/{concept}/descendants:
    get:
      tags:
        - lookup
      summary: 'Return descendants (subclasses or subproperties) of concept, based on the BioLink Model YAML'
      description: ''
      parameters:
        - in: path
          required: true
          name: concept
          default: chemical_substance
        - in: query
          name: version
          default: latest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /bl/{concept}/lineage:
    get:
      tags:
        - lookup
      summary: 'Return the ancestors and descendants of concept, based on the BioLink Model YAML'
      description: ''
      parameters:
        - in: path
          required: true
          name: concept
          default: chemical_substance
        - in: query
          name: version
          default: latest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /uri_lookup/{uri}:
    get:
      tags:
        - lookup
      summary: 'Given the URI for a property, return the corresponding BioLink Model slot. Checks the Biolink Model YAML for both slot_uri and mappings.'
      description: ''
      parameters:
        - in: path
          required: true
          name: uri
          example: RO:0002606
        - in: query
          name: version
          default: latest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /bl/{concept}:
    get:
      tags:
        - lookup
      summary: 'Get all properties for concept from the BioLink Model YAML.'
      description: ''
      parameters:
        - in: path
          required: true
          name: concept
          default: chemical_substance
        - in: query
          name: version
          default: latest
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
  /versions:
    get:
      tags:
        - meta
      summary: 'Get available BioLink Model versions. These values can be used to parameterize other function calls.'
      description: ''
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string